// Copyright 2024 the dancelist authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

pub const BANDS: [&str; 578] = [
    "112 and Then Some",
    "A Cat's Tale",
    "A Fine Kettle of Fish",
    "A Joyful Noise",
    "Abacus",
    "Accentricity",
    "Accords Perdus",
    "Achterband",
    "Adam Rich-Griffin & Nicola McConkey",
    "AdHoc Orkest",
    "Adriano Sangineto",
    "Aérokorda",
    "Air de Famille",
    "Airboxes",
    "Akleja",
    "Alchemy",
    "All Keyed Up",
    "AlleMonOh Stringband",
    "Amarillis & Anders",
    "Amberwing",
    "Anadama",
    "Andrea Capezzuoli",
    "Andrea Hoag",
    "Andreas Neumann",
    "Androneda",
    "Andy Cutting",
    "Angelika Hudler & Laurenz Schiffermüller",
    "Antanjo",
    "Anytime English Players",
    "Appalachian Roots",
    "Arcotones",
    "Artisjok",
    "Atlantic Crossing",
    "Att Dansa",
    "Aubergine",
    "Aurélien Claranbaux",
    "Autour de Bâle",
    "Avalance",
    "Avourneen",
    "ba.fnu",
    "Baby Corns",
    "Back Row Band",
    "Bal à Sept",
    "Bal Affaire",
    "Bal O'Gadjo",
    "Balbuzar",
    "Ball Noir",
    "Ballkanesen",
    "Ballo Allegro",
    "Bamako Express",
    "Bandage a Trois",
    "Banna Damhsa",
    "Bare Necessities",
    "Bargainatt",
    "Barock op de Deel",
    "Bart Praet",
    "Bearded Dragons",
    "Beat Bouet Trio",
    "Bellamira",
    "Ben Bolker & Susanne Maziarz",
    "Benjamin Rowe & Adam Rich-Griffin",
    "Berkenwerk",
    "Big Brandy",
    "Big Fun",
    "Biskaya",
    "Black Cat Quadrille",
    "Blind Squirrel",
    "Bluejay",
    "BmB",
    "Boccadoro",
    "Bodarc",
    "Bokpojkarna",
    "Bosnick & Bittel",
    "Bougnat Sound",
    "Bourrée Party Crackers",
    "Bouton",
    "Bowrider",
    "Box and String Trio",
    "Box of Frogs",
    "Boxwood",
    "Brasstown Balfolk Band",
    "Brazenkeys",
    "Brickyard Joes",
    "Broes",
    "Brook Farm String Band",
    "Brooklyn Swing Ensemble",
    "Budweis-Wunderlich",
    "Bunny Bread Bandits",
    "Calico",
    "Calliope",
    "Cardboard Cabin",
    "Carin Greve",
    "Cecilia",
    "Celtic Connection",
    "Celtic Constellation",
    "Chablis",
    "Chaotic Good",
    "Cheap Shots",
    "Chicken Feathers",
    "Chimney Swift",
    "Chrástu",
    "Chris Liakos & John Wetzel",
    "Ciac Boum",
    "Ciona",
    "CLARABAL",
    "Cojiro",
    "Constellation",
    "Contra Banditos",
    "Contra Fusion",
    "Contra Intuitive",
    "Contra Sutra",
    "ContraForce",
    "Contrary Faeries",
    "Contrasaurus",
    "Contratopia",
    "Contraverts",
    "Coral Riff",
    "Cosmic Otters",
    "Countercurrent",
    "Crossover Duo",
    "Crossover Trio",
    "Danse Café",
    "Danzvogel",
    "David Cornelissen",
    "David James & Craig Johnson",
    "De Houtzagerij",
    "De Trekvogels",
    "Dead Sea Squirrels",
    "Definitely Contraband",
    "Devilish Mary",
    "Die Dudelsacksen",
    "Die Hayner",
    "Die ZWEI",
    "DJ TacoShel",
    "Djîga",
    "Dodging Pheasants",
    "Dogtown",
    "Dos en Trío",
    "Doxatunes",
    "Dragon Fire",
    "Dreamy Folk Flow",
    "Drehwurm",
    "Drive Train",
    "Drøn",
    "Duet Friends",
    "Duo Absynthe",
    "Duo Baftig",
    "Duo Bottasso",
    "Duo Brotto Milleret",
    "Duo Clercx",
    "Duo Coudroy Genet",
    "Duo du Balcon",
    "Duo FA",
    "Duo Gielen-Buscan",
    "Duo l'Hêtre Heureux",
    "Duo Mackie/Hendrix",
    "Duo Montanaro-Cavez",
    "Duo Nello",
    "Duo NoLa",
    "Duo Obsessie",
    "Duo Pacher-Roblin",
    "Duo Roblin-Thébaut",
    "Duo Super Nova",
    "Duo Thézé",
    "Duo Torv",
    "Duo Vandenabeele-Knapen",
    "Duo Wolff-Moschcau",
    "DURRbanda",
    "Edentia",
    "Eins68",
    "Elba Connection",
    "Elegant Echoes",
    "Elixir",
    "Eloise & Co.",
    "EmBRUN",
    "Emelie Waldken",
    "Emily & The Simons",
    "Emma & Jonas",
    "Engine Room",
    "English Contra Dance Band",
    "Erik en Martijn",
    "Euphor",
    "Ewout & Anouk",
    "Exqueezit",
    "Fahrenheit",
    "Fat Fiddles",
    "Feather and Fox",
    "Fiddle Hellions Big Band",
    "Fiddle Hellions",
    "Fiddlechicks",
    "Filippo Gambetta",
    "Fior",
    "Firletanz",
    "First Time Stringband",
    "Fjellerkene",
    "Flatland Consort",
    "Floris & the Flames",
    "Flour City Doughboys",
    "Flying Cat",
    "Flying Romanos",
    "Folie du Nord",
    "Folk Knock",
    "Folk Voice Band",
    "Folkinger",
    "Folkschwestern Biese",
    "Fourpence",
    "Free Association",
    "French Toast",
    "Friends of Virgil",
    "Froghammer",
    "Full Tilt",
    "Fyndus",
    "Fyr Freya",
    "Gaelstorm",
    "Gammeldansk",
    "George Paul",
    "Geronimo",
    "GIG CB!",
    "Ginger Jam",
    "Ginkgo",
    "Gisbert",
    "Go Figure",
    "Good Company",
    "Good Intentions",
    "Gott Folk!",
    "Göze",
    "Grace Haaland",
    "Grand Balthazar",
    "Grand Picnic",
    "Gray & Friends",
    "GrayScale",
    "Green Willow",
    "Greg & Aiden Boardman",
    "Gribouille",
    "Griff Trio",
    "Groove Factory",
    "Guillaume Sparrow-Pepin & Rachel Bell",
    "Hale Bill & the Bopps",
    "Harken!",
    "Hartwin Dhoore Trio",
    "Hartwin Dhoore",
    "Havok",
    "Headwaters",
    "Here on the Hill",
    "High Drive",
    "High Strung",
    "Hijinks",
    "Hoggetowne Fancy",
    "Hoik",
    "Holiday Ball Orchestra",
    "Hoosier Recruits",
    "Hora Fani",
    "Hot Coffee Breakdown",
    "Hot Griselda",
    "Hot Toddy",
    "Hypergolic",
    "I Pizzicati",
    "Ice Cream Truckers",
    "Idlewild",
    "Irish Diplomacy",
    "Javallon",
    "Jeroen Laureyssens",
    "Jet Bridge",
    "Joachim Montbord",
    "Joanna Hyde & Tadhg O Meachair",
    "Jormsons Kapell",
    "Joy Factor",
    "Joyance",
    "Joyride",
    "Jumping Sharks",
    "Jumpstart",
    "Kabál",
    "Kaleidoscope",
    "Kaléidoscope",
    "Kaw Creek",
    "Kelten zonder Grenzen",
    "Kikker & Findus",
    "KinFyre",
    "Kingfisher",
    "Klintetten",
    "Kördeböf",
    "Koriander",
    "KV Express",
    "Kvinnene",
    "L'air Inconnu",
    "L’equipe",
    "La Belle Ivresse",
    "La Bonne Soupe",
    "La Machine",
    "La Mézanj",
    "La Réveilleuse",
    "La Sauterelle",
    "LAB 160",
    "LAB162",
    "Lackawanna Longnecks",
    "Lagomorph Trio",
    "Lake Effect",
    "Laouen",
    "Larks in the Attic",
    "Laurie Fisher & Nik Coker",
    "Le Carillon",
    "Le Driadi",
    "Le Mange Bal",
    "Leben & Schwarz",
    "Les Bottines Artistiques",
    "Les Kickeuses",
    "Les Quatre Patates",
    "Les QuetscheKaschde",
    "Les Zéoles",
    "Leveret",
    "Liberty String Band",
    "Light Migrations",
    "Lizzy's Cocktail",
    "Local On-Call Orchestra",
    "Lone Star Pirates",
    "Long Forgotten String Band",
    "Loose Shoes",
    "Lovely Lane String Band",
    "Luca Fiorini",
    "Lys&Co",
    "Madlot",
    "Magistal",
    "MaJoPlus",
    "MANdolinMAN",
    "Manesse Hopp",
    "Mara Menzel",
    "Maracu",
    "Marbelous Daves",
    "Marfinara",
    "Marie Paulette",
    "Martina & Gisbert & Rainer",
    "Matt Norman & Edward Wallace",
    "Matt Norman & Hannah Cummings",
    "Matt Norman",
    "Mavro Meli",
    "Meadowhawk",
    "Merriment",
    "MetroGnomes",
    "Mevilish Merry",
    "Mickey Koth & John Kalinowski",
    "Midnight on the Water",
    "Mieneke",
    "Millserati",
    "Miriquidi",
    "Moab Community Dance Band",
    "Mockingbird",
    "Momiro",
    "Monday Night All Stars",
    "Mook",
    "Moore & Moss",
    "Morceau de Breizh",
    "Morrison Brothers",
    "Mound City Slickers",
    "Mr Folxlide",
    "Musac",
    "Mystic Gorillas",
    "Nachtmuziek",
    "Naragonia Quartet",
    "Naragonia",
    "Naredi",
    "Nebel",
    "New Hoosier Broadcasters",
    "Night Heron",
    "Noiranomis",
    "Nordic Exposure",
    "Norrsken",
    "North Dixie Boom Chicks",
    "Northern Aire",
    "Northwoods",
    "Notorious",
    "Nova",
    "Nozzy",
    "Nubia",
    "Nut en Genoegen",
    "Odevare",
    "Oh CONTRAire",
    "Old Time All Stars",
    "Olivier Valence",
    "OMGDude",
    "Ormuz",
    "Pamplemousse",
    "Paracetamol",
    "Paradocs",
    "Parasol",
    "Penny Farthing",
    "Persons of Quality",
    "Peter Michealsen & Joe Finn",
    "PFM!",
    "Philu",
    "Pimento Mori",
    "Plan B",
    "Playing with Fyre",
    "Plönk",
    "Pont Ondulé",
    "Portland Megaband",
    "Portmanteau",
    "Quicksilver",
    "QuiVive",
    "Ragged Robin",
    "Ratatouille",
    "Raven & Goose",
    "Red Case Band",
    "Red Dog Riley",
    "Reelplay",
    "Rémi Geffroy",
    "Rest 'n' Peas",
    "Rhys Jones and the Imaginary Beings",
    "River Music",
    "River Road",
    "Roguery",
    "Rokkende Vrouwen",
    "Root System",
    "Round Hill Ramblers",
    "Rum & Onions",
    "Sail Away Ladies",
    "Seattle Lilla Spelmanslag",
    "Seattle Skandia Spelmanslag",
    "Senior Moment",
    "Serendipity",
    "Shandy",
    "Shillelagh",
    "Sigmar Gothe",
    "Simone Bottasso",
    "Sister Haggis",
    "Six Feet Back",
    "Skandia Kapell",
    "Skavidra",
    "Smith, Campeau & Nelson",
    "Snaarmaarwaar",
    "Snapdragon",
    "Snappin' Bug Stringband",
    "Snorty Horse",
    "Soldo",
    "Solid Ghost",
    "Southwind",
    "Sparv",
    "Spintuition",
    "Sprida Ut",
    "Spring Chickens",
    "SpringTide",
    "Starling",
    "StatiK",
    "Steam!",
    "Stefano Baldan",
    "Steppin' Stones",
    "Stepwise",
    "Stomp Rocket",
    "Stomping Ground",
    "Stove Dragon",
    "Stringrays",
    "Strings on Wings",
    "Stromlosplus",
    "Sture und Sigmar",
    "Supertrad",
    "Swartematerie",
    "Swinco",
    "Swingology",
    "Sycamore",
    "Tabbies Delight",
    "Take a Dance",
    "Taranteira",
    "Tea & Whiskey",
    "Tea for Three",
    "Thalas",
    "The 32 Bartenders",
    "The Atchisons",
    "The Black Cat Quadrille",
    "The Boom Chicks",
    "The Brickersons",
    "The Campeau Creek Boys",
    "The Chivalrous Crickets",
    "The Contra Rebels",
    "The Dam Beavers",
    "The English Muffins",
    "The Evil Twins",
    "The Faux Paws",
    "The Fiddling Thomsons",
    "The Flying Elbows",
    "The Free Raisins",
    "The French Connection",
    "The Gaslight Tinkers",
    "The Guys",
    "The Hollertones",
    "The Jig Lords",
    "The Johns",
    "The Latter Day Lizards",
    "The Little Big Band",
    "The Lost Keys",
    "The McKenzies",
    "The Moving Violations",
    "The Orphans",
    "The Outsiders",
    "The Rafter Ringers",
    "The Rythmajigs",
    "The Star Charters",
    "The String Bean Serenaders",
    "The Syncopaths",
    "The Tater Bugs",
    "The Third Degree",
    "The Turning Stile",
    "The Usual Suspects",
    "Thorn Among the Roses",
    "Threo",
    "Thunderwing",
    "TinnFelen",
    "Toad Holler",
    "Toad in the Hole",
    "Toil and Treble",
    "Tom & Aurélie",
    "Toot, Squeeze & Co.",
    "Tooth Pickers",
    "Toppish",
    "Topspin",
    "Torrent",
    "Toss the Possum",
    "TradTöchter",
    "Tralala Lovers",
    "Treble Play",
    "Tref",
    "Triaz",
    "Tribal Jâze",
    "Trillium",
    "Trio Baftig",
    "Trio Con Brio",
    "Trio Loubelya",
    "Trio Mirambel",
    "TriOblique",
    "Trip Hazard",
    "Trip to Norwich",
    "Triple-X",
    "Triptych",
    "Trouveur Valdoten",
    "Tunebuggy",
    "Turnip the Beet",
    "Two Catch a Raindrop",
    "Two Hats",
    "Ultra Tagada",
    "Unbowed",
    "Unipot",
    "Uppsala",
    "Ute+Michael",
    "Vagalan",
    "Valentin Barray",
    "Vandiekomsa",
    "Viadeyra",
    "Viola Voilá",
    "Vionelles",
    "Virginia Creepers",
    "Vlier",
    "Wabi Sabi",
    "Wakarusa Roundabouts",
    "Wake Up Robin",
    "Warleggan Village Band",
    "Warmoes",
    "Waterbound String Band",
    "Waverley Station",
    "Wee Merry Banshees",
    "Weirdstrings",
    "Wergleyberg",
    "Westside Warblers",
    "Wheels of the World",
    "Whirled Peas",
    "Wild Asparagus",
    "Wild Notes",
    "Wild Thistle",
    "Wild Wombats of the Chesapeake",
    "WillPower",
    "Wilma",
    "Wim te Groen",
    "Windsor Knot",
    "Wings & Tales",
    "Wissahickon Express",
    "Wouter en de Draak",
    "Wouter Kuyper",
    "Wry Bred",
    "YanYana",
    "Yanyk",
    "Zéphyr Combo",
];
