// Copyright 2024 the dancelist authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

pub const BANDS: [&str; 351] = [
    "112 and Then Some",
    "A Fine Kettle of Fish",
    "A Joyful Noise",
    "Abacus",
    "Achterband",
    "Adam Rich-Griffin & Nicola McConkey ",
    "AdHoc Orkest",
    "Aérokorda",
    "Air de Famille",
    "Airboxes",
    "Akleja",
    "AlleMonOh Stringband",
    "Amarillis & Anders",
    "Andrea Capezzuoli",
    "Andreas Neumann",
    "Androneda",
    "Andy Cutting",
    "Antanjo",
    "Anytime English Players",
    "Appalachian Roots",
    "Artisjok",
    "Atlantic Crossing",
    "Aubergine",
    "Aurélien Claranbaux",
    "Autour de Bâle",
    "Avalance",
    "Avourneen",
    "Back Row Band",
    "Bal O'Gadjo",
    "Ball Noir",
    "Ballkanesen",
    "Ballo Allegro",
    "Bamako Express",
    "Bare Necessities",
    "Bargainatt",
    "Barock op de Deel",
    "Bart Praet",
    "Bearded Dragons",
    "Beat Bouet Trio",
    "Bellamira",
    "Ben Bolker & Susanne Maziarz",
    "Benjamin Rowe & Adam Rich-Griffin",
    "Berkenwerk",
    "Big Fun",
    "Biskaya",
    "Blind Squirrel",
    "BmB",
    "Boccadoro",
    "Bougnat Sound",
    "Bourrée Party Crackers",
    "Bouton",
    "Box and String Trio",
    "Box of Frogs",
    "Brasstown Balfolk Band",
    "Brazenkeys",
    "Broes",
    "Brook Farm String Band",
    "Bunny Bread Bandits",
    "Calico",
    "Cardboard Cabin",
    "Carin Greve",
    "Cecilia",
    "Chablis",
    "Chaotic Good",
    "Chicken Feathers",
    "Chimney Swift",
    "Chris Liakos & John Wetzel",
    "Ciac Boum",
    "Ciona",
    "Cojiro",
    "Constellation",
    "Contra Banditos",
    "Contra Intuitive",
    "ContraForce",
    "Contrary Faeries",
    "Contrasaurus",
    "Contraverts",
    "Coral Riff",
    "Countercurrent",
    "Crossover Duo",
    "Crossover Trio",
    "Danzvogel",
    "David Cornelissen",
    "De Houtzagerij",
    "De Trekvogels",
    "Dead Sea Squirrels",
    "Devilish Mary",
    "Die Hayner",
    "Die ZWEI",
    "DJ TacoShel",
    "Dodging Pheasants",
    "Dogtown",
    "Dragon Fire",
    "Dreamy Folk Flow",
    "Drehwurm",
    "Drive Train",
    "Drøn",
    "Duo Absynthe",
    "Duo Baftig",
    "Duo Bottasso",
    "Duo Clercx",
    "Duo Gielen-Buscan",
    "Duo l'Hêtre Heureux",
    "Duo Mackie/Hendrix",
    "Duo Nello",
    "Duo Pacher-Roblin",
    "Duo Roblin-Thebaut",
    "Duo Thézé",
    "Duo Torv",
    "Duo Wolff-Moschcau",
    "Edentia",
    "Eins68",
    "Elba Connection",
    "Elixir",
    "Eloise & Co.",
    "EmBRUN",
    "Emelie Waldken",
    "Emily & The Simons",
    "Engine Room",
    "English Contra Dance Band",
    "Erik en Martijn",
    "Euphor",
    "Ewout & Anouk",
    "Exqueezit",
    "Fahrenheit",
    "Feather and Fox",
    "Fiddlechicks",
    "Fior",
    "First Time Stringband",
    "Flour City Doughboys",
    "Flying Cat",
    "Flying Romanos",
    "Folie du Nord",
    "Folkinger",
    "Folkschwestern Biese",
    "Fourpence",
    "French Toast",
    "Froghammer",
    "Full Tilt",
    "Fyndus",
    "George Paul",
    "Geronimo",
    "Gisbert",
    "Go Figure",
    "Good Company",
    "Good Intentions",
    "Gott Folk!",
    "Göze",
    "Grand Picnic",
    "GrayScale",
    "Guillaume Sparrow-Pepin & Rachel Bell",
    "Harken!",
    "Hartwin Dhoore Trio",
    "Hartwin Dhoore",
    "Havok",
    "Headwaters",
    "High Drive",
    "Hijinks",
    "Hoggetowne Fancy",
    "Holiday Ball Orchestra",
    "Hot Coffee Breakdown",
    "Hot Griselda",
    "Hot Toddy",
    "I Pizzicati",
    "Irish Diplomacy",
    "Javallon",
    "Jeroen Laureyssens",
    "Joachim Montbord",
    "Joanna Hyde & Tadhg O Meachair",
    "Jormsons Kapell",
    "Joyance",
    "Joyride",
    "Jumping Sharks",
    "Kaw Creek",
    "Kelten zonder Grenzen",
    "Kikker & Findus",
    "Kingfisher",
    "Kördeböf",
    "KV Express",
    "L'air Inconnu",
    "L’equipe",
    "La Belle Ivresse",
    "La Bonne Soupe",
    "La Réveilleuse",
    "La Sauterelle",
    "Lackawanna Longnecks",
    "Lagomorph Trio",
    "Lake Effect",
    "Laouen",
    "Larks in the Attic",
    "Laurie Fisher & Nik Coker",
    "Les Bottines Artistiques",
    "Les Kickeuses",
    "Les Zéoles",
    "Leveret",
    "Liberty String Band",
    "Lizzy's Cocktail",
    "Lone Star Pirates",
    "Long Forgotten String Band",
    "Lovely Lane String Band",
    "Luca Fiorini",
    "Lys&Co",
    "Madlot",
    "Magistal",
    "MaJoPlus",
    "Mara Menzel",
    "Maracu",
    "Marbelous Daves",
    "Marfinara",
    "Marie Paulette",
    "Martina & Gisbert & Rainer",
    "Matt Norman & Edward Wallace",
    "Matt Norman & Hannah Cummings",
    "Mavro Meli",
    "Merriment",
    "Mevilish Merry",
    "Midnight on the Water",
    "Mieneke",
    "Moab Community Dance Band",
    "Momiro",
    "Mook",
    "Moore & Moss",
    "Morceau de Breizh",
    "Mr Folxlide",
    "Musac",
    "Nachtmuziek",
    "Naragonia Quartet",
    "Naragonia",
    "Nebel",
    "New Hoosier Broadcasters",
    "Night Heron",
    "Noiranomis",
    "Northern Aire",
    "Notorious",
    "Nova",
    "Nozzy",
    "Nubia",
    "Olivier Valence",
    "Ormuz",
    "Pamplemousse",
    "Paracetamol",
    "Parasol",
    "Persons of Quality",
    "PFM!",
    "Philu",
    "Pimento Mori",
    "Playing with Fyre",
    "Pont Ondulé",
    "Portland Megaband",
    "QuiVive",
    "Ragged Robin",
    "Red Case Band",
    "Red Dog Riley",
    "Reelplay",
    "Rémi Geffroy",
    "River Music",
    "River Road",
    "Rokkende Vrouwen",
    "Round Hill Ramblers",
    "Rum & Onions",
    "Sail Away Ladies",
    "Serendipity",
    "Shandy",
    "Shillelagh",
    "Simone Bottasso",
    "Sister Haggis",
    "Smith, Campeau & Nelson",
    "Snaarmaarwaar",
    "Snappin' Bug Stringband",
    "Soldo",
    "Sparv",
    "Spintuition",
    "SpringTide",
    "Starling",
    "Stomp Rocket",
    "Stove Dragon",
    "Stringrays",
    "Strings on Wings",
    "Stromlosplus",
    "Supertrad",
    "Swinco",
    "Swingology",
    "Sycamore",
    "Take a Dance",
    "Thalas",
    "The Atchisons",
    "The Black Cat Quadrille",
    "The Boom Chicks",
    "The Brickersons",
    "The Campeau Creek Boys",
    "The Dam Beavers",
    "The English Muffins",
    "The Faux Paws",
    "The Fiddling Thomsons",
    "The Flying Elbows",
    "The Free Raisins",
    "The French Connection",
    "The Gaslight Tinkers",
    "The Hollertones",
    "The Ice Cream Truckers",
    "The Little Big Band",
    "The Moving Violations",
    "The Orphans",
    "The Rafter Ringers",
    "The String Bean Serenaders",
    "The Syncopaths",
    "The Third Degree",
    "The Turning Stile",
    "Toad Holler",
    "Toad in the Hole",
    "Toss the Possum",
    "Tralala Lovers",
    "Tref",
    "Tribal Jaze",
    "Trillium",
    "Trio Baftig",
    "Trio Con Brio",
    "Trio Loubelya",
    "TriOblique",
    "Trip Hazard",
    "Trip to Norwich",
    "Triple-X",
    "Triptych",
    "Trouveur Valdoten",
    "Tunebuggy",
    "Two Catch a Raindrop",
    "Two Hats",
    "Ultra Tagada",
    "Unbowed",
    "Ute+Michael",
    "Vagalan",
    "Vandiekomsa",
    "Viola Voilá",
    "Wabi Sabi",
    "Wakarusa Roundabouts",
    "Warleggan Village Band",
    "Waterbound String Band",
    "Wee Merry Banshees",
    "Wergleyberg",
    "Westside Warblers",
    "Wheels of the World",
    "Wild Asparagus",
    "Wild Wombats of the Chesapeake",
    "Wilma",
    "Wim te Groen",
    "Wings & Tales",
    "Woody & the Westside Warblers",
    "Wouter en de Draak",
    "Wouter Kuyper",
    "Wry Bred",
    "Yanyk",
];
